zeebe:
  client:
    cloud:
      clusterId: eb4ecdfb-9875-4744-8dda-9dd1134f9231
      clientId: mP2pv8_Ys5v5fsKP4QEAtuTRim~r4jMI
      clientSecret: Ayp8G03WQj5FcEFxxxZLR9SbdefXQmgzFXQs2idmT7Tah.sHBW1ztPDX6jx57Iv~